apiVersion: v1
kind: Secret
metadata:
  name: hivemind-platform-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.jwtSecret | quote }}
  REDIS_PASSWORD: {{ .Values.redisPassword | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresPassword | quote }}
  MONGODB_PASSWORD: {{ .Values.mongodbPassword | default "" | quote }}
  VONAGE_API_KEY: {{ .Values.vonageApiKey | quote }}
  VONAGE_API_SECRET: {{ .Values.vonageApiSecret | quote }}
