creation_rules:
  - path_regex: environments/prod/secrets\.yaml$
    age: "age1enhnld965kmczdmehvfgv7enk9khh0ygevpaflt2vjv02f3kz9zqq4qy98"
  - path_regex: environments/staging/secrets\.yaml$
    age: "age1enhnld965kmczdmehvfgv7enk9khh0ygevpaflt2vjv02f3kz9zqq4qy98"
