apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.name" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  TWILIO_ACCOUNT_SID: {{ .Values.secrets.TWILIO_ACCOUNT_SID | quote }}
  TWILIO_AUTH_TOKEN: {{ .Values.secrets.TWILIO_AUTH_TOKEN | quote }}
  TWILIO_PHONE_NUMBER: {{ .Values.secrets.TWILIO_PHONE_NUMBER | quote }}
