apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.name" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
