apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-uploads
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "service.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
