apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.name" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | quote }}
  AWS_ACCESS_KEY: {{ .Values.secrets.AWS_ACCESS_KEY | quote }}
  AWS_SECRET_KEY: {{ .Values.secrets.AWS_SECRET_KEY | quote }}
